const sentenceParts = {
    subjects: [
      "Frodo",
      "Gandalf",
      "Aragorn",
      "Legolas",
      "Gimli",
      "Sam",
      "Merry",
      "Pippin",
      "Boromir",
    ],
    verbs: [
      "fought against",
      "traveled with",
      "discovered",
      "protected",
      "defeated",
      "encountered",
      "befriended",
      "escaped from",
      "confronted",
    ],
    objects: [
      "the One Ring",
      "the Balrog",
      "Sauron",
      "Gollum",
      "Saruman",
      "the orcs",
      "the Nazgûl",
      "the ents",
      "the Uruk-hai",
    ],
  };